name: Build and deploy DAB to Azure Web App - dab-thundercode-dotnet

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js (to enable npm start)
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Download DAB (.NET build) into backend-dab
        working-directory: backend-dab
        run: |
          curl -L https://github.com/Azure/data-api-builder/releases/download/v1.4.35/dab_net8.0_linux-x64-1.4.35.zip -o dab.zip
          unzip -o dab.zip

      - name: Zip artifact for deployment
        run: zip -r release.zip ./backend-dab/*

      - name: Upload artifact for deployment job
        uses: actions
